Delrio homework week2 apis class45
HackYourAssignment/Homework-class45 pull request #84
Opened 2023-10-17 21:25 UTC by Lenindelrionicaragua

2023-10-21 11:38 UTC, abbathaw requested changes
Good job on ex1.

I will give this a second review once you add the missing exercises.

You also included week 1 in this PR. Please make sure Week 2 PR doesn't include your old commits.

- Checkout main
- Create a new branch for week 2
- Push the branch as your new homework PR

2023-10-21 11:38 UTC, abbathaw commented on 3-UsingAPIs/Week2/homework/ex1-programmerFun/index.js
> +    });
You don't need to catch and inside the catch throw the same error (no point). Since the main function which is calling this requestData function is already wrapped in a try and catch.

You can also try using async await here instead of the `.then`

2023-10-26 13:48 UTC, Lenindelrionicaragua commented
https://github.com/HackYourAssignment/Homework-class45/pull/87

I apologize for the confusion. I'm not sure what happened, but my exercises were uploaded blank. I have now fixed the issue, and they are complete. I'm looking forward to your review

2023-11-28 12:24 UTC, closed without merging

2023-11-28 12:24 UTC, abbathaw commented
Closing this as you have uploaded a different PR for the homework instead of updating this one. Make sure you update and/or close the PRs yourself in future situations 🙂

New PR is here https://github.com/HackYourAssignment/Homework-class45/pull/87

2023-11-29 13:21 UTC, Lenindelrionicaragua commented
I'm very sorry, you're absolutely right. I didn't know the process well,
that's why I updated it directly on GitHub before; syncing this version was
enough. I'll make sure this error doesn't happen again.

El mar, 28 nov 2023 a las 13:24, Abdullah ***@***.***>)
escribió:

> Closing this as you have uploaded a different PR for the homework instead
> of updating this one. Make sure you update and/or close the PRs yourself in
> future situations 🙂
>
> New PR is here #87
> <https://github.com/HackYourAssignment/Homework-class45/pull/87>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/HackYourAssignment/Homework-class45/pull/84#issuecomment-1829738124>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BB3YWEAV6Z3GG3U4ADPPDJDYGXJXXAVCNFSM6AAAAAA6EPTLF2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMRZG4ZTQMJSGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>